export const NIGERIA_STATES: Record<string, string[]> = {
  Abia: ["Aba", "Umuahia", "Ohafia", "Arochukwu"],
  Adamawa: ["Yola", "Mubi", "Numan", "Jimeta"],
  "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene", "Oron"],
  Anambra: ["Awka", "Onitsha", "Nnewi", "Ekwulobia"],
  Bauchi: ["Bauchi", "Azare", "Misau", "Jama'are"],
  Bayelsa: ["Yenagoa", "Brass", "Nembe", "Ogbia"],
  Benue: ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala"],
  Borno: ["Maiduguri", "Biu", "Bama", "Dikwa"],
  "Cross River": ["Calabar", "Ikom", "Ogoja", "Ugep"],
  Delta: ["Asaba", "Warri", "Sapele", "Ughelli"],
  Ebonyi: ["Abakaliki", "Afikpo", "Onueke", "Ezza"],
  Edo: ["Benin City", "Auchi", "Ekpoma", "Uromi"],
  Ekiti: ["Ado-Ekiti", "Ikere", "Ijero", "Oye"],
  Enugu: ["Enugu", "Nsukka", "Agbani", "Oji River"],
  Gombe: ["Gombe", "Deba", "Kaltungo", "Billiri"],
  Imo: ["Owerri", "Orlu", "Okigwe", "Mbaise"],
  Jigawa: ["Dutse", "Hadejia", "Gumel", "Birnin Kudu"],
  Kaduna: ["Kaduna", "Zaria", "Kafanchan", "Kagoro"],
  Kano: ["Kano", "Wudil", "Gwarzo", "Bichi"],
  Katsina: ["Katsina", "Dutsin-Ma", "Funtua", "Malumfashi"],
  Kebbi: ["Birnin Kebbi", "Argungu", "Yauri", "Zuru"],
  Kogi: ["Lokoja", "Okene", "Idah", "Kabba"],
  Kwara: ["Ilorin", "Offa", "Omu-Aran", "Lafiagi"],
  Lagos: ["Ikeja", "Lagos Island", "Lekki", "Ikorodu", "Badagry", "Epe"],
  Nasarawa: ["Lafia", "Keffi", "Akwanga", "Karu"],
  Niger: ["Minna", "Bida", "Kontagora", "Suleja"],
  Ogun: ["Abeokuta", "Sagamu", "Ijebu-Ode", "Ota"],
  Ondo: ["Akure", "Ondo", "Owo", "Ikare"],
  Osun: ["Osogbo", "Ile-Ife", "Ilesa", "Ede"],
  Oyo: ["Ibadan", "Ogbomoso", "Oyo", "Saki"],
  Plateau: ["Jos", "Bukuru", "Pankshin", "Shendam"],
  Rivers: ["Port Harcourt", "Bonny", "Degema", "Eleme"],
  Sokoto: ["Sokoto", "Tambuwal", "Gwadabawa", "Illela"],
  Taraba: ["Jalingo", "Wukari", "Bali", "Gembu"],
  Yobe: ["Damaturu", "Potiskum", "Gashua", "Nguru"],
  Zamfara: ["Gusau", "Kaura Namoda", "Talata Mafara", "Anka"],
  FCT: ["Abuja", "Gwagwalada", "Kuje", "Bwari"],
};

export const NIGERIA_STATE_NAMES = Object.keys(NIGERIA_STATES).sort();
