import type { Catalog, Course, Instructor } from "./index";

export const seedInstructors: Instructor[] = [
  {
    id: "ins_amara",
    slug: "amara-cole",
    name: "Amara Cole",
    role: "Graphic Design Lead",
    bio: "Brand designer who has built identity systems for education, retail, and civic organisations. Amara teaches visual decision-making — type, colour, hierarchy — so career switchers leave with a portfolio that reads as professional, not classroom.",
    initials: "AC",
    accent: "blue",
    courseSlugs: ["graphic-design"],
  },
  {
    id: "ins_nico",
    slug: "nico-alvarez",
    name: "Nico Alvarez",
    role: "Front-End Lead",
    bio: "Interface engineer focused on accessible, fast websites. Nico spent years turning design files into production UI and now coaches newcomers through HTML, CSS, and modern JavaScript without skipping the fundamentals.",
    initials: "NA",
    accent: "red",
    courseSlugs: ["front-end-development", "full-stack-development"],
  },
  {
    id: "ins_priya",
    slug: "priya-raman",
    name: "Priya Raman",
    role: "Backend Lead",
    bio: "API and data specialist. Priya designs services that stay boring under load: clear HTTP, honest databases, and auth that does not leak. She taught herself into engineering and structures the backend track for the same path.",
    initials: "PR",
    accent: "blue",
    courseSlugs: ["backend-development", "full-stack-development"],
  },
  {
    id: "ins_owen",
    slug: "owen-blake",
    name: "Owen Blake",
    role: "Full Stack Lead",
    bio: "Product engineer who ships the whole slice: interface, API, deploy. Owen runs the capstone like a studio — scoped, reviewed, and demoed — so full-stack students finish with something they can put in front of a hiring manager.",
    initials: "OB",
    accent: "red",
    courseSlugs: ["full-stack-development"],
  },
];

const gdOutline: Course["outline"] = [
  { week: 1, title: "Seeing like a designer", hours: 8, topics: ["Visual hierarchy", "Contrast and alignment", "Critique language"], project: null },
  { week: 2, title: "Type as structure", hours: 8, topics: ["Pairing Nexa-class geometrics", "Scale and rhythm", "Typesetting for screens"], project: "Poster: one message, two weights" },
  { week: 3, title: "Colour systems", hours: 8, topics: ["Limited palettes", "Brand blue / signal red", "Accessible contrast"], project: null },
  { week: 4, title: "Composition and layout", hours: 8, topics: ["Grids", "Negative space", "Editorial vs marketing"], project: "Magazine spread for a course page" },
  { week: 5, title: "Figma as craft", hours: 8, topics: ["Components", "Auto-layout", "Export discipline"], project: null },
  { week: 6, title: "Identity", hours: 8, topics: ["Marks vs wordmarks", "Clear space", "Misuse cases"], project: "Mini identity for a local service" },
  { week: 7, title: "Digital campaigns", hours: 8, topics: ["Social frames", "Stories vs feed", "Motion stills"], project: null },
  { week: 8, title: "Production files", hours: 8, topics: ["Print vs web", "PDF/X awareness", "Handoff notes"], project: "Campaign kit (5 assets)" },
  { week: 9, title: "UX-adjacent design", hours: 8, topics: ["Landing structure", "Forms that feel calm", "Empty states"], project: null },
  { week: 10, title: "Portfolio editing", hours: 8, topics: ["Case-study writing", "Before/after", "Process, not decoration"], project: "First case study draft" },
  { week: 11, title: "Client simulation", hours: 8, topics: ["Brief intake", "Two directions", "Presenting choices"], project: null },
  { week: 12, title: "Ship the book", hours: 8, topics: ["Final critique", "Personal site layout", "How to talk about the work"], project: "Portfolio of 3 pieces" },
];

const feOutline: Course["outline"] = [
  { week: 1, title: "The web as documents", hours: 8, topics: ["HTML landmarks", "Semantics over divs", "Browser tools"], project: null },
  { week: 2, title: "CSS that holds", hours: 8, topics: ["Cascade and specificity", "Flex and grid", "Custom properties"], project: "Split-layout landing clone" },
  { week: 3, title: "Type and rhythm on the web", hours: 8, topics: ["Fluid type", "Self-hosted fonts", "CLS prevention"], project: null },
  { week: 4, title: "Responsive without breakpoints soup", hours: 8, topics: ["Mobile-first dock/rail", "Container queries", "Touch targets"], project: "Fully responsive syllabus page" },
  { week: 5, title: "JavaScript as behaviour", hours: 8, topics: ["DOM events", "Fetch", "Progressive enhancement"], project: null },
  { week: 6, title: "Accessibility is the job", hours: 8, topics: ["Keyboard paths", "ARIA only when needed", "Colour is not the only signal"], project: "Audit and repair a page" },
  { week: 7, title: "Modern UI components", hours: 8, topics: ["Forms", "Dialogs", "Status messages"], project: null },
  { week: 8, title: "A component library of one", hours: 8, topics: ["Build vs buy", "State", "Folder discipline"], project: "Small design-system slice" },
  { week: 9, title: "Talking to APIs", hours: 8, topics: ["JSON", "Loading and error UI", "Auth headers"], project: null },
  { week: 10, title: "Performance", hours: 8, topics: ["Images", "Fonts", "What not to ship"], project: "Lighthouse pass on your project" },
  { week: 11, title: "Git and deploy", hours: 8, topics: ["PRs as conversation", "Static hosting", "Env vs secrets"], project: null },
  { week: 12, title: "Capstone interface", hours: 8, topics: ["Scope freeze", "Demo", "Portfolio write-up"], project: "Public UI for a real brief" },
];

const beOutline: Course["outline"] = [
  { week: 1, title: "HTTP without the mystery", hours: 8, topics: ["Methods and status", "Headers", "JSON as a contract"], project: null },
  { week: 2, title: "Node as a server", hours: 8, topics: ["Runtime", "Routing", "Env config"], project: "Health + echo API" },
  { week: 3, title: "Data you can trust", hours: 8, topics: ["Relational thinking", "SQLite/Postgres", "Migrations"], project: null },
  { week: 4, title: "CRUD that is actually correct", hours: 8, topics: ["Validation", "Ids", "Error shapes"], project: "Resource API with tests" },
  { week: 5, title: "Auth sessions", hours: 8, topics: ["Password hashing", "Cookies", "CSRF awareness"], project: null },
  { week: 6, title: "Files and evidence", hours: 8, topics: ["Uploads", "MIME allow-lists", "Private storage"], project: "Receipt upload endpoint" },
  { week: 7, title: "Business rules", hours: 8, topics: ["Transactions", "Seat caps", "Idempotent register"], project: null },
  { week: 8, title: "Security basics", hours: 8, topics: ["Injection", "Rate limits", "Secrets"], project: "Threat notes on your API" },
  { week: 9, title: "Jobs and mail", hours: 8, topics: ["Transactional email", "Retries", "Logs"], project: null },
  { week: 10, title: "Observability", hours: 8, topics: ["Request ids", "Structured logs", "Healthchecks"], project: null },
  { week: 11, title: "Ship it", hours: 8, topics: ["Docker-lite", "Backups", "Env per stage"], project: null },
  { week: 12, title: "Capstone service", hours: 8, topics: ["Review", "Load of the happy path", "Handoff README"], project: "Production-shaped API" },
];

const fsOutline: Course["outline"] = [
  { week: 1, title: "The slice", hours: 8, topics: ["What full stack means here", "Tooling", "Git from day one"], project: null },
  { week: 2, title: "Interface foundations", hours: 8, topics: ["Semantic HTML", "CSS layout", "Accessible forms"], project: null },
  { week: 3, title: "Server foundations", hours: 8, topics: ["HTTP", "Validation", "Databases"], project: "Register endpoint" },
  { week: 4, title: "Auth across the stack", hours: 8, topics: ["Sessions", "Tokens for status pages", "Never store raw tokens"], project: null },
  { week: 5, title: "A real product surface", hours: 8, topics: ["Information architecture", "Empty/error/success"], project: "Public + admin split" },
  { week: 6, title: "Files, mail, money-adjacent", hours: 8, topics: ["Uploads", "Evidence review", "Audit logs"], project: null },
  { week: 7, title: "Front-end quality", hours: 8, topics: ["Performance budget", "SEO HTML", "No SPA by default"], project: null },
  { week: 8, title: "Back-end quality", hours: 8, topics: ["Transactions", "Rate limits", "Backups"], project: null },
  { week: 9, title: "Studio week", hours: 8, topics: ["Scope freeze", "User testing", "Rewrite the copy"], project: "Mid-capstone critique" },
  { week: 10, title: "Hardening", hours: 8, topics: ["Security pass", "Privacy copy", "File retention"], project: null },
  { week: 11, title: "Deploy both sides", hours: 8, topics: ["Static site + API", "CORS", "Health"], project: null },
  { week: 12, title: "Polish", hours: 8, topics: ["OG images", "Sitemap", "Analytics without bloat"], project: null },
  { week: 13, title: "Hiring artefacts", hours: 8, topics: ["README", "Architecture note", "Demo script"], project: null },
  { week: 14, title: "Feature complete", hours: 8, topics: ["Bug bash", "Seat-cap edge cases"], project: null },
  { week: 15, title: "Rehearsal", hours: 8, topics: ["Live demo", "Q&A as an engineer"], project: null },
  { week: 16, title: "Ship and tell", hours: 8, topics: ["Public URL", "Case study", "Next learning plan"], project: "Capstone live + write-up" },
];

export const seedCourses: Course[] = [
  {
    id: "crs_gd",
    slug: "graphic-design",
    name: "Graphic Design",
    shortPitch: "Learn to make visual systems that hold up in the real world — identity, layout, and a portfolio you can stand behind.",
    durationWeeks: 12,
    weeklyHours: 8,
    price: 450,
    currency: "USD",
    seatCap: 24,
    registrationOpen: true,
    outcomes: [
      "Design with hierarchy, type, and a limited palette",
      "Build a small identity and campaign kit in Figma",
      "Write a case study that explains decisions, not just mood",
      "Present two directions to a simulated client",
    ],
    outline: gdOutline,
    tools: ["Figma", "Adobe Photoshop", "Adobe Illustrator", "Google Fonts discipline / self-hosted type"],
    prerequisites: "A laptop that can run Figma. No prior design job required. Curiosity about how things look — and why — is enough.",
    faq: [
      { q: "Is this only software training?", a: "No. Tools are vehicles. You will spend more time on critique, hierarchy, and finishing work than on menu tours." },
      { q: "Can complete beginners join?", a: "Yes. The track is built for career switchers and people new to visual work, with extra studio hours in the first month." },
    ],
    ogDescription: "Virtual 12-week Graphic Design training at UPSCALE. Identity, type, campaigns, and a portfolio — live online.",
    instructorIds: ["ins_amara"],
    sortOrder: 1,
  },
  {
    id: "crs_fe",
    slug: "front-end-development",
    name: "Front-End Development",
    shortPitch: "Build interfaces that load fast, read clearly, and work on a phone. HTML, CSS, JavaScript — taught as a craft, not a framework fashion show.",
    durationWeeks: 12,
    weeklyHours: 8,
    price: 550,
    currency: "USD",
    seatCap: 20,
    registrationOpen: true,
    outcomes: [
      "Ship responsive pages without a UI kit crutch",
      "Write JavaScript that enhances HTML, not replaces it",
      "Meet accessibility and performance baselines",
      "Deploy a public interface and explain the structure",
    ],
    outline: feOutline,
    tools: ["VS Code", "Git / GitHub", "HTML / CSS / JavaScript", "Browser DevTools"],
    prerequisites: "Comfortable installing software and typing. No computer-science degree. A willingness to debug is more important than prior code.",
    faq: [
      { q: "Will we start with React?", a: "Not in week one. You will earn the platform first. Component thinking arrives once documents, CSS, and accessibility are in your hands." },
      { q: "Is the course virtual live?", a: "Yes. Live sessions twice a week, recordings for catch-up, and critiques on your actual pages." },
    ],
    ogDescription: "Virtual 12-week Front-End Development training at UPSCALE. HTML, CSS, JavaScript, accessibility, and a public capstone.",
    instructorIds: ["ins_nico"],
    sortOrder: 2,
  },
  {
    id: "crs_be",
    slug: "backend-development",
    name: "Backend Development",
    shortPitch: "Learn the server side properly: HTTP, data, auth, files, and the rules that keep student and payment data from leaking.",
    durationWeeks: 12,
    weeklyHours: 8,
    price: 550,
    currency: "USD",
    seatCap: 20,
    registrationOpen: true,
    outcomes: [
      "Design JSON APIs with validation and honest errors",
      "Store data in a real database with migrations",
      "Handle uploads, sessions, and audit logs",
      "Ship a service with healthchecks and backups in mind",
    ],
    outline: beOutline,
    tools: ["Node.js", "SQL", "Git", "HTTP clients", "Linux basics for deploy"],
    prerequisites: "Some exposure to programming syntax helps, but the track is open to determined newcomers. You will write code every week.",
    faq: [
      { q: "Which language?", a: "JavaScript/TypeScript on Node — one runtime, fewer moving parts, and a straight path into full stack if you continue." },
      { q: "Do I need cloud experience?", a: "No. We introduce deploy as a discipline in the last third, after the API is correct on your machine." },
    ],
    ogDescription: "Virtual 12-week Backend Development training at UPSCALE. APIs, databases, auth, uploads, and production habits.",
    instructorIds: ["ins_priya"],
    sortOrder: 3,
  },
  {
    id: "crs_fs",
    slug: "full-stack-development",
    name: "Full Stack Development",
    shortPitch: "Sixteen weeks from first page to live product: interface, API, payment-adjacent flows, and a capstone you can demo.",
    durationWeeks: 16,
    weeklyHours: 8,
    price: 850,
    currency: "USD",
    seatCap: 16,
    registrationOpen: true,
    outcomes: [
      "Own both sides of a small product",
      "Keep the public site fast and crawlable",
      "Build an admin desk for real operations",
      "Deploy, document, and present the work",
    ],
    outline: fsOutline,
    tools: ["HTML / CSS / JS", "Node.js", "SQL", "Git", "Static hosting + a small API host"],
    prerequisites: "Best if you can already write a simple page or follow a tutorial to the end. Complete beginners should start on Front-End or Backend, then join a later full-stack cohort.",
    faq: [
      { q: "Is this two courses glued together?", a: "No. You build one product across sixteen weeks. Front-end and backend are taught in the order the product needs them." },
      { q: "How heavy is the time?", a: "Plan for 8 hours in session plus 4–6 hours of studio work. Career switchers should treat it like a part-time job." },
    ],
    ogDescription: "Virtual 16-week Full Stack Development training at UPSCALE. Ship a public site and an operations API as one product.",
    instructorIds: ["ins_owen", "ins_nico", "ins_priya"],
    sortOrder: 4,
  },
];

export const seedCatalog: Catalog = {
  settings: {
    tagline: "learn today, build tomorrow",
    heroLine: "Virtual training for people changing direction — into design, into code, or further along the path they already started.",
    proof: [
      { value: "Live", label: "virtual classrooms" },
      { value: "4", label: "career tracks" },
      { value: "12–16", label: "weeks per cohort" },
      { value: "8h", label: "guided each week" },
    ],
    bank: {
      bankName: "Set in admin",
      accountName: "UPSCALE Training",
      accountNumber: "0000000000",
      instructions: "Transfer the exact cohort fee. Put your UPSCALE reference in the narration. Then upload the receipt on the payment page.",
    },
    timezone: "GMT+1",
    email: "frank.g@example.org",
    whatsapp: "+234 803 059 9638",
    registrationOpen: true,
    closedMessage: "This intake is closed. Join the waitlist by writing to frank.g@example.org.",
    faqs: [
      { q: "Who is UPSCALE for?", a: "People switching career path, people new to the IT space, and people who already work adjacent to design or engineering and want to upscale with a structured cohort." },
      { q: "Is it virtual?", a: "Yes. Live sessions online, with recordings. You need a laptop, a stable connection, and a quiet two-hour window on class days." },
      { q: "How do I pay?", a: "Bank transfer using the reference we email you. Upload payment evidence on your private payment page. A human verifies it before you are enrolled." },
      { q: "Do I get a certificate?", a: "Yes, after you complete the capstone and the cohort closes. The stronger artefact is the work itself." },
      { q: "What if I miss a class?", a: "Recordings go out the same day. You are still expected to submit studio work; this is not a YouTube playlist with a price tag." },
      { q: "Refunds?", a: "If we decline your evidence because of a genuine error, you may re-upload. Fee refunds after enrolment are handled in writing against the cohort policy in your confirmation email." },
    ],
  },
  courses: seedCourses,
  instructors: seedInstructors,
  cohorts: [
    {
      id: "coh_gd_26a",
      courseSlug: "graphic-design",
      startDate: "2026-09-14",
      endDate: "2026-12-04",
      daysLabel: "Mon & Wed",
      timeLabel: "18:00–20:30",
      timezone: "GMT+1",
      seatCap: 24,
      seatsTaken: 0,
      price: 450,
      currency: "USD",
    },
    {
      id: "coh_fe_26a",
      courseSlug: "front-end-development",
      startDate: "2026-09-15",
      endDate: "2026-12-05",
      daysLabel: "Tue & Thu",
      timeLabel: "18:00–20:30",
      timezone: "GMT+1",
      seatCap: 20,
      seatsTaken: 0,
      price: 550,
      currency: "USD",
    },
    {
      id: "coh_be_26a",
      courseSlug: "backend-development",
      startDate: "2026-09-15",
      endDate: "2026-12-05",
      daysLabel: "Tue & Thu",
      timeLabel: "18:00–20:30",
      timezone: "GMT+1",
      seatCap: 20,
      seatsTaken: 0,
      price: 550,
      currency: "USD",
    },
    {
      id: "coh_fs_26a",
      courseSlug: "full-stack-development",
      startDate: "2026-09-21",
      endDate: "2027-01-10",
      daysLabel: "Mon & Thu",
      timeLabel: "18:00–20:30",
      timezone: "GMT+1",
      seatCap: 16,
      seatsTaken: 0,
      price: 850,
      currency: "USD",
    },
  ],
};
